### ISSUE TITLE
Staking twice to the same node from the same wallet

### ISSUE THREAD

**Issue by tylerjohneddy** [EquilibriaCC/Equilibria#101]
I staked into node ID 052468f25fa4753a04865dcea2c4866abda0bf20216f81e53cf47be0066aa69d with an amount which is showing on the node explorer and the funds show as locked in my wallet

I then wanted to increase my stake so ran the same command from the same wallet, the funds are locked in my wallet but the node explorer doesn't show my additional contributions nor has my rewards increased.

Any support would be appreciated!

**Comment by GreggyGB** [comment]
Explorer is adding up both stakes into one. I tried to replicate your issue and my result basically added up both stakes into one line
