### ISSUE TITLE
Staking on own Node from same wallet stopped Node's reward

### ISSUE THREAD

**Issue by invizib** [EquilibriaCC/Equilibria#107]
I have setup Service Node Public Key: 4b83152dad0f333fb69fcc7288216fb9d9362fb6690166ad203c141f780b7477 
Was receiving about 3.53 as reward.
I staked on a random Service Node just to test and got both Node and Staking rewards.

So I staked more coins on my own node from the same wallet address and I'm now receiving less reward (3.02).
I expected to receive both part of the block's reward, not only the staking part.

**Comment by BKdilse** [comment]
On someone else's node, it's fine to do, but there is a max of 35000 XEQ for the Node Operator stake, which you have now exceeded on your own node, which is why the rewards are only being received for the extra amount above 35K.

I had a similar issue, as I over staked by only 15 XEQ !!!

**Comment by baldtrooper** [comment]
So you can't run and stake on the same node from the same wallet?

**Comment by invizib** [comment]
> Sort of makes sense but would have been nice to be told

Yeah, I would have expected some sort of warning or not being able to stake on my node because my maximum stake is reached on the node side.

**Comment by BKdilse** [comment]
Yeah, I guess we were told in a cryptic way, the words 35K Max for operator is the message lol.

The way around it of course is to stake anything above 35K, using another wallet.
