### ISSUE TITLE
wXEQ->XEQ Bridge Swaps Stuck

### ISSUE THREAD

**Issue by weisiteX** [EquilibriaCC/Equilibria#108]
Hashes here for bridge swaps:
0x16c1904c068d38645ae4f3f612447b5a05b959ad322877a533ad52e731c4b8ca
0xf757b3decef6e933315e01f2a051f509546c5e91f820effc079b3deca59ce73e

Amounts are 1000 and 900. The "check swap" function seems to say "Waiting..." for any hash that is put into the box. 

Also, when speeding up a transaction for token access approval the portal seems to "lose" the transaction and I have to authorize a new approval *without* speeding it up.

**Comment by AdminXeq** [comment]
wXEQ under review
