### ISSUE TITLE
Non-Operator Stakers Limited to 30K Max for Staking vs 65K

### ISSUE THREAD

**Issue by djp1701** [EquilibriaCC/Equilibria#110]
It appears that regular stakers, in total, are only able to stake 30K as opposed to 65K.  With that, the total staked amount, including the operator, is 65K instead of 100K.

**Comment by BKdilse** [comment]
I've this too, and forgot to raise it.
A 35K Operator staked node will only accept 30K from stakers.
A 30K Operator staked node allows the remaining 35K from stakers.

So, 65K appears to be the Max.

**Comment by pcbreflux** [comment]
Not one of the actual 97 nodes are below the 35k ... see https://www.snxeq.info/

**Comment by BKdilse** [comment]
65K limit, not 35K. Can't go beyond 64K.
