### ISSUE TITLE
Failed to open wallet. Version: ATOM v2.0.1-v0.5.0.2

### ISSUE THREAD

**Issue by hookscpp** [EquilibriaCC/Equilibria#112]
After updating the client, I get an error: "Failed to open wallet". Is this corrupted and is there a patch? My wallet password is 100% correct.

Version: ATOM v2.0.1-v0.5.0.2

**Comment by AdminXeq** [comment]
Please test with newest wallet version 13.2.0 and if error persists, raise another issue
