### ISSUE TITLE
My wallet has no XEQ?

### ISSUE THREAD

**Issue by Frankiemai** [EquilibriaCC/Equilibria#114]
I have opened my wallet and it says 0 XEQ?

**Comment by Frankiemai** [comment]
> Sync it

Hi, how please GUI windows, i am not familiar with this.

**Comment by Frankiemai** [comment]
> 

I have retrieved the wallet from seed and it is still 0. But thank you I will try Discord.

**Comment by AdminXeq** [comment]
Rescan with new release 13.2.0 GUI or cli
