### ISSUE TITLE
Node Staking Limited to 65K vs. 100K

### ISSUE THREAD

**Issue by djp1701** [EquilibriaCC/Equilibria#119]
It appears that node staking is limited to 65K max as opposed to the intended 100K.  As a result, a node will never become fully staked and considered a full node.  You can see on the explorer that many of the open nodes have 35K remaining.

e.g.
A 35K Operator staked node will only accept 30K from stakers vs 65K, 
A 30K Operator staked node allows the remaining 35K from stakers vs. 70K, etc.

This entry references the recently closed issue, #110

**Comment by djp1701** [comment]
Any updates as to whether or not this will be addressed in the next release?  The maximum staking amount was supposed to be 100K total at the release of v12...35 max for operators and 65 max for stakers.  As a result of this oversight, no nodes are ever fully staked.  ;)  Thank you!

**Comment by AdminXeq** [comment]
Should be fixed on next release
