### ISSUE TITLE
Equilibria New Dev - suggestions

### ISSUE THREAD

**Issue by RayCar2022** [EquilibriaCC/Equilibria#120]
Hi,

Suggestions:

- Draft new White Paper 
- Draft new Tokenomics
- Open bridge wXEQ to XEQ
- Each staking node to show what is accurately left to stake so one doesn't have to keep trying different amounts

Thank you.

**Comment by AdminXeq** [comment]
Announcement will be made shortly

**Comment by RayCar2022** [comment]
Hi, why not wait to close until the announcement has been made?
