### ISSUE TITLE
wXEQ Support

### ISSUE THREAD

**Issue by XEQLP** [EquilibriaCC/Equilibria#121]
Hi team, we are a small group of long time wXEQ supporters/LPs who would like to offer support on the wXEQ side of the project. Would be happy to discuss any ideas the team has and help wherever we can. Please shoot us a DM if interested! 

https://twitter.com/xeqlpteam

**Comment by AdminXeq** [comment]
Feel free to follow https://twitter.com/EquilibriaDevs
Any support is appreciated
