### ISSUE TITLE
Weekly or Bi-weekly Update

### ISSUE THREAD

**Issue by XEQLP** [EquilibriaCC/Equilibria#122]
Hey team, we'd like to recommend a set day every week for an update to the community. For example, TOMB has Tomb Tuesdays. Periods of silence and a lack of updates have always negatively impacted this project. We think a weekly check in would be a huge reassurance to the community and boost the credibility/transparency of the new team. We've got some weekly metrics/ideas that we'd like to contribute to the updates if the team would like to implement this. Hope to hear from you guys!

https://twitter.com/xeqlpteam

**Comment by djp1701** [comment]
I would suggest Thursdays!

**Comment by gab81** [comment]
that's a great initiative - could be also bi-weekly if weekly is too much and perhaps not enough news on a weekly basis? (although i really like the idea).

**Comment by AdminXeq** [comment]
It is often the case that the development team is working on several solutions at once and it takes a longer test to release patches. We will try to inform as soon as possible, but a longer silence means one thing, the team is working on the code and solutions. We will try to get you up to date as soon as possible

**Comment by djp1701** [comment]
@AdminXeq...it was the long silence that resulted in the state we were in previously.  Even if there is nothing significant to offer, a quick message informing that work is ongoing, even small successes, would be enough to regain faith in the project.  Regaining that faith, once it is lost, is extremely difficult, if not impossible, as there will always be that thought that the project will again be abandon.  At this point...the more communication, the better.

**Comment by RayCar2022** [comment]
Agreed with djp1701's message above.
