### ISSUE TITLE
Node Staking Limited to 65K vs. 100K

### ISSUE THREAD

**Issue by djp1701** [EquilibriaCC/Equilibria#135]
The issue previously reported in #110 and #119 persists after the recent fork.  The maximum amount of XEQ that can be staked is still 65K when combining node operator with regular stakers.  As a result, we will never have full nodes registered on the network.  While I am sure that this issue doesn't affect rewards, it does not help the network as a whole.

Error: You may not contribute any more to this service node

        Total Contributed/Staking Requirement: 65000.0000/100000.0000
        Total Reserved: 65000.0000

**Comment by baldtrooper** [comment]
Not sure if this can be upvoted but if so then I do! fixing this would allow 3.5million more XEQ to be staked with the same amount of nodes. This will help the price be more stable giving those holding the coin the ability to stake. I've added 4 more nodes in the last 2 days and all filled within about 2hrs of being live. Please make this the no1 fix in the next release.

**Comment by AdminXeq** [comment]
The patch is already done. To have it Live at MainNet will require HardFork which we are preparing at the moment along with new XEQ <-> wXEQ Swap Bridge and new contracts to invalidate old ones. We will keep you updated about.
To 100k stake requirement. It is divided between Operator (35k) + Open-Node-Contributors (65k)

**Comment by baldtrooper** [comment]
Perfect! Thanks
