### ISSUE TITLE
Wallet sync issue with RPC on v18

### ISSUE THREAD

**Issue by BKdilse** [EquilibriaCC/Equilibria#148]
Version:
`Equilibria 'Galileo Galilei' (v18.0.0-991a7edb0)`

Start up command line:
`daemon --rpc-bind-ip 0.0.0.0 --confirm-external-bind --restricted-rpc`

When connecting remotely to sync wallet, the following error appears, and the wallet cannot be synced:
`Error: refresh failed: RPC error: error in /gettransactions RPC: Too many transactions requested in restricted mode. Blocks received: 0`

Used to work fine in the previous release.

**Comment by malbit** [comment]
transaction fetching hasn't beed changed recently and v17 and v18 use same rules. Restricted_rpc_tx_count is set to 100 now and before.

**Comment by BKdilse** [comment]
That's strange, I got the same issue on 2 different nodes I run, both are on my local network.  I'll do some more testing today, and update here.

**Comment by BKdilse** [comment]
Restarted Daemon to be sure, and still has the same issue.
I can confirm it works fine when I remove `--restricted-rpc`

Can anyone else confirm this issue?

**Comment by djp1701** [comment]
Yes...I can confirm the same issue and resolution.

**Comment by AdminXeq** [comment]
v19 with  parameters  
./daemon --rpc-bind-ip 0.0.0.0 --rpc-bind-port 9231 --confirm-external-bind --non-interactive 
Solve problem
