### ISSUE TITLE
Daemon will not print version

### ISSUE THREAD

**Issue by BigslimVdub** [EquilibriaCC/Equilibria#149]
V18.0.0 Daemon

Issue:
While Daemon is running, unable to print the version of daemon. 
Before starting daemon, unable to print the version of daemon.

Error:
version                                                                          
Error: The daemon software version is not available.

**Comment by BKdilse** [comment]
Can confirm I see this too.

**Comment by AdminXeq** [comment]
./daemon --rpc-bind-ip 0.0.0.0 --rpc-bind-port 9231 --confirm-external-bind --non-interactive
Present v19 version
