### ISSUE TITLE
Algorithm of mining proposal to randomARQ

### ISSUE THREAD

**Issue by AdminXeq** [EquilibriaCC/Equilibria#158]
Since the cn_GPU algorithm is highly power-hungry, a proposal was made to change it to a variant from RandomX.
Our proposal is to use the most efficient and compatible CPU-based randomARQ algorithm. It is faster and requires less L2 cache, so it can be used on low end CPUs. It is even possible to mine on a Raspberry Pi. There will be a vote soon on whether we stick with CN-GPU or implement RandomARQ

**Comment by BigslimVdub** [comment]
I approve of this request if we can name it RandomXEQ

**Comment by AdminXeq** [comment]
RandomXEQ repo on GitHub

**Comment by realsetvin** [comment]
Need help with anything or testing?
