### ISSUE TITLE
remote node

### ISSUE THREAD

**Issue by ArqTras** [EquilibriaCC/Equilibria#26]
Portland 5.0.2 remote node
51.158.65.16:9230

**Comment by swa74** [comment]
How do I sync daemon ? ERROR blockchain src/cryptonote_core/blockchain.cpp:3660 !!!!!!!!! difficulty overhead !!!!!!!!!

**Comment by ArqTras** [comment]
—add-exclusive-node 51.158.65.16:9230 
and use latest binaries

**Comment by swa74** [comment]
/equilibria/build/Linux/_HEAD_detached_at_v5.0.2_/release/bin$ ./daemon --add-exclusive-node 51.158.65.16:9230
2020-01-29 05:08:30.524 [P2P8]  ERROR   blockchain      src/cryptonote_core/blockchain.cpp:3660 !!!!!!!!! difficulty overhead !!!!!!!!!

**Comment by swa74** [comment]
Thank you, it seems to have gone after deleting the folder .equilibria
