### ISSUE TITLE
a JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by nuro-project** [EquilibriaCC/Equilibria#54]
Windows 10
default diectory settings

![equiibria](https://user-images.githubusercontent.com/84205663/121788856-db950f00-cb85-11eb-9145-2175721393eb.png)

**Comment by GrahamboJangles** [comment]
I have a similar problem. I can't access my wallet with money in it.

![image](https://user-images.githubusercontent.com/36944031/161488475-b2f2bce6-4231-4901-a2f3-19715de3ce44.png)
