### ISSUE TITLE
Error in wallet2.cpp function parse_uri (line 13469)

### ISSUE THREAD

**Issue by pcbreflux** [EquilibriaCC/Equilibria#70]
Produces an Error message for every uri:

"message": "Error parsing URI: URI has wrong scheme (expected \"equilibria:\"):

Line 13469:

> if (uri.substr(0, 7) != "equilibria:")  

should be 

> if (uri.substr(0, 11) != "equilibria:")

to fit the whole string "equilibria:"

(from original code ... if (uri.substr(0, 7) != "monero:"))

**Comment by HarrisonHesslink** [comment]
Thanks! Fixed in #82
