### ISSUE TITLE
i had an issue with password starting with capitalized character 

### ISSUE THREAD

**Issue by michaelhjulskov** [EquilibriaCC/Equilibria#81]
i had an issue with linux cli wallet 
issue was password starting with capitalized character would not allow me to send funds out of my wallet
i reported this issue/bug in details in the telegram group but emediately got kicked 
but who cares right - its not important that people can send their funds 
im sure this will be deleted as well
great - whatever

**Comment by HarrisonHesslink** [comment]
Not sure why you were kicked on telegram. The easiest way to get back to having access to your funds is to create a new wallet from the restore from seed function. You can do this by `--wallet-cli --restore-from-seed ` and following the prompts.

**Comment by michaelhjulskov** [comment]
i fixed my issue long time ago - ITS NOT ABOUT ME - IM TRYING TO HELP!!!!! but nobody seems to have a brain around here, sorry im so tired of sending feedback about this.

everybody else who experienced this issue (just because they chose a password with capitalized first letter) dont know how they could fix this. They dont know its a software bug. They most likely just give up after several attempts.

I am not impressed -  normally developers love to get feedback

**Comment by michaelhjulskov** [comment]
YOU kicked me out - so ask yourself, why you kicked me out.
YOU also got me kicked from TCV on telegram

**Comment by HarrisonHesslink** [comment]
I didn't kick you, nor did I get you kicked off the TCV telegram. I will check out this bug. Thanks for the feedback.

**Comment by michaelhjulskov** [comment]
Youre welcome
I think it was some guy named Greg that kicked me from xeq telegram group - he also sent me some private messages, an I do not answer that kind of messages from totally strangers, I prefer the public feedback and comments.
An when I told people on TCV about this, then I was kicked from TCV emmediately after that Greg dude commented it and attacked me.
I might confuse you with that Greg character, cause he seemed to be admin and kicked me.
I actually posted this issue/bug also many months ago and at that time I was also kicked..
Look - feedback is important - especially when there is bugs and issues in software and on the official website.

By the way there is two different links on the linux download page:
https://www.equilibria.network/integration/linux
also the versioning in the link text is not correct - and its not linking to the latest release as it says in the link. and the "Description" link doesnt do anything.
in my opinion there should be simply two links. one that points to the latest gui wallet and one that points to the latest cli wallet and maybe a third link that helps people installing and/or tell the known bugs/issues and how to work around those issues

**Comment by anushuiac** [comment]
Admins never dm first. Maybe it was a fake Greg.
If you want to report bugs, do it here or join discord and post it in #community-bug-findings thread.
Also tcv has nothing to do with xeq. They are a separate group.
These bugs were reported already. There are some minor bugs like this or about website links, but consider the project is in early stage of developments and loyal members you should be more patient.
Some priorities are more important for dev.

As I remember my password started with capital letter but, had no issue sending my funds. But using some special chars may cause problem.

In cli wallet there was an issue, when wallet goes in Sleep mode and you want to send funds, you could write only one character of your password/ or you may not able to navigate through commands history with up/ down keys. You needed to restart the wallet to transfer your coins.
I saw this bug in other cn coin wallets.

**Comment by michaelhjulskov** [comment]
Hi @AdminXeq  :)
Was the issue actually solved or is this issue report just closed

**Comment by AdminXeq** [comment]
Try 13.2.0 , if there is still problem please open new issue.
Thanks for support

**Comment by michaelhjulskov** [comment]
I wont try it or test it. 
I dont care about this project anymore. 

Not my problem. 
And... i was kicked from the telegram group because i reported this issue, so ....whoever did that can go.....

Just felt sorry for people who couldnt transfer their funds because of this stupid issue.
